# Generated by Django 4.2 on 2025-04-06 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 11, 31, 34, 578512, tzinfo=datetime.timezone.utc)),
        ),
    ]
