# Generated by Django 4.2 on 2025-04-06 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 11, 36, 32, 406501, tzinfo=datetime.timezone.utc)),
        ),
    ]
