# Generated by Django 4.2 on 2025-04-06 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 11, 39, 44, 537398, tzinfo=datetime.timezone.utc)),
        ),
    ]
