# Generated by Django 4.2 on 2025-04-06 16:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expiration',
            field=models.DateTimeField(default=users.models.default_expiration),
        ),
    ]
