# Generated by Django 4.2 on 2025-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_donations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
