# Generated by Django 5.1.7 on 2025-03-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="comment_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comments.commentreply",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("comment", "Comment"),
                    ("comment_reply", "CommentReply"),
                ],
                max_length=15,
            ),
        ),
    ]
